spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: doc-application
            client-secret: WsMzj9SfvxA3HuKraObMXbfWIWhMdsDE
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/documents
            user-name-attribute: preferred_username